/**
 * Type-only SDK surface for the editor facade. GraphQL transport and generated
 * documents live in the trusted MCP runtime; the extension never imports them
 * at runtime.
 */
export type {
	Sdk,
	SdkFunctionWrapper,
	AddAllowedToolMutation,
	AddAllowedToolMutationVariables,
	ConversationFragment,
	ConversationMessageFragment,
	CreateConversationMessageVoteMutation,
	CreateConversationMessageVoteMutationVariables,
	CreateTemplateMinimalMutation,
	CreateTemplateMinimalMutationVariables,
	DeleteConversationMutation,
	DeleteConversationMutationVariables,
	DeleteTemplateMutation,
	DeleteTemplateMutationVariables,
	FullTemplateFragment,
	GetConversationQuery,
	GetConversationQueryVariables,
	GetConversationsQuery,
	GetConversationsQueryVariables,
	GetTemplateQuery,
	GetTemplateQueryVariables,
	ListTemplatesQuery,
	ListTemplatesQueryVariables,
	MyRoboRewstyPreferencesQuery,
	MyRoboRewstyPreferencesQueryVariables,
	OrgFragment,
	RemoveAllowedToolMutation,
	RemoveAllowedToolMutationVariables,
	RoboRewstyPreferencesFragment,
	TemplateFragment,
	UpdateTemplateBodyMutation,
	UpdateTemplateBodyMutationVariables,
	UpdateTemplateMutation,
	UpdateTemplateMutationVariables,
	UpdateTemplateNameMutation,
	UpdateTemplateNameMutationVariables,
	UserFragment,
	UserQuery,
	UserQueryVariables,
} from '../../../packages/mcp-server/src/sessions/graphql/sdk';
